version: "3.8"
services:
  sentinel-api:
    build: .
    container_name: sentinel_backend
    ports:
      - "8000:8000"
    volumes:
      # Sinkronisasi folder database agar data tidak hilang saat kontainer dimatikan
      - ./database:/app/database
    restart: unless-stopped
